// flow-typed signature: a5a03cfde862e0330bbf4d4a4fa5de55
// flow-typed version: <<STUB>>/coffeescript_v1.12.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffeescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffeescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffeescript/lib/coffee-script/browser' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/cake' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/coffee-script' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/command' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/grammar' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/helpers' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/index' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/lexer' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/nodes' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/optparse' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/parser' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/register' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/repl' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/rewriter' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/scope' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffee-script/sourcemap' {
  declare module.exports: any;
}

declare module 'coffeescript/register' {
  declare module.exports: any;
}

declare module 'coffeescript/repl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffeescript/lib/coffee-script/browser.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/browser'>;
}
declare module 'coffeescript/lib/coffee-script/cake.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/cake'>;
}
declare module 'coffeescript/lib/coffee-script/coffee-script.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/coffee-script'>;
}
declare module 'coffeescript/lib/coffee-script/command.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/command'>;
}
declare module 'coffeescript/lib/coffee-script/grammar.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/grammar'>;
}
declare module 'coffeescript/lib/coffee-script/helpers.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/helpers'>;
}
declare module 'coffeescript/lib/coffee-script/index.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/index'>;
}
declare module 'coffeescript/lib/coffee-script/lexer.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/lexer'>;
}
declare module 'coffeescript/lib/coffee-script/nodes.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/nodes'>;
}
declare module 'coffeescript/lib/coffee-script/optparse.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/optparse'>;
}
declare module 'coffeescript/lib/coffee-script/parser.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/parser'>;
}
declare module 'coffeescript/lib/coffee-script/register.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/register'>;
}
declare module 'coffeescript/lib/coffee-script/repl.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/repl'>;
}
declare module 'coffeescript/lib/coffee-script/rewriter.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/rewriter'>;
}
declare module 'coffeescript/lib/coffee-script/scope.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/scope'>;
}
declare module 'coffeescript/lib/coffee-script/sourcemap.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffee-script/sourcemap'>;
}
declare module 'coffeescript/register.js' {
  declare module.exports: $Exports<'coffeescript/register'>;
}
declare module 'coffeescript/repl.js' {
  declare module.exports: $Exports<'coffeescript/repl'>;
}
