// flow-typed signature: 9d09f6858ee977ebe4f69aabf47d9aff
// flow-typed version: <<STUB>>/@rails/webpacker_v^3.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rails/webpacker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rails/webpacker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rails/webpacker/package/asset_host' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environment' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/development' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/production' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/test' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/index' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/babel' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/coffee' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/elm' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/erb' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/file' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/style' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/typescript' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/loaders/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rails/webpacker/package/asset_host.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/asset_host'>;
}
declare module '@rails/webpacker/package/config.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config'>;
}
declare module '@rails/webpacker/package/environment.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environment'>;
}
declare module '@rails/webpacker/package/environments/development.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/development'>;
}
declare module '@rails/webpacker/package/environments/production.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/production'>;
}
declare module '@rails/webpacker/package/environments/test.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/test'>;
}
declare module '@rails/webpacker/package/index.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/index'>;
}
declare module '@rails/webpacker/package/loaders/babel.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/babel'>;
}
declare module '@rails/webpacker/package/loaders/coffee.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/coffee'>;
}
declare module '@rails/webpacker/package/loaders/elm.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/elm'>;
}
declare module '@rails/webpacker/package/loaders/erb.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/erb'>;
}
declare module '@rails/webpacker/package/loaders/file.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/file'>;
}
declare module '@rails/webpacker/package/loaders/style.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/style'>;
}
declare module '@rails/webpacker/package/loaders/typescript.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/typescript'>;
}
declare module '@rails/webpacker/package/loaders/vue.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/loaders/vue'>;
}
